kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: same-az-test
nodes:
  - role: control-plane
  - role: worker
    labels:
      topology.kubernetes.io/region: us-east-1
      topology.kubernetes.io/zone: us-east-1a
  - role: worker
    labels:
      topology.kubernetes.io/region: us-east-1
      topology.kubernetes.io/zone: us-east-1b
  - role: worker
    labels:
      topology.kubernetes.io/region: us-east-1
      topology.kubernetes.io/zone: us-east-1c
